apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    app: ngnix-deployment
spec:
  selector:
    matchLabels:
      app: ngnix-deployment
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: ngnix-deployment
    spec:
      
      containers:
      - name: udacitycapstoneproject
        image: mohmagdy1016/udacitycapstoneproject
        imagePullPolicy: Always
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Service
metadata:
  name: ngnix-deployment
spec:
  type: LoadBalancer
  selector:
    app: ngnix-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    
