apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
    selector:
       matchLabels:
         app: nginx
    strategy:
       type: RollingUpdate
       rollingUpdate:
           maxUnavailable: 75%
    replicas: 3
    template:
      metadata:
        labels:
          app: nginx
      spec:
          containers:
            - name: udacitycapstoneproject 
              imagePullPolicy: Always
              image: mohmagdy1016/udacitycapstoneproject:latest
              ports:
              - containerPort: 80
           
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80